####################
# Alacritty config #
####################

# Spawn new instance in same directory
key_bindings:
  - { key: Return,   mods: Super|Shift, action: SpawnNewInstance }

window:
  dimensions:
    columns: 88
    lines: 28

font:
  normal:
    family: "Hack"
    style: Regular
  bold:
    family: "Hack"
    style: Bold
  italic:
    family: "Hack"
    style: Italic
  bold_italic:
    family: "Hack"
    style: Bold Italic
