####################
# Alacritty config #
####################

# Spawn new instance in same directory
key_bindings:
  - { key: Return,  mods: Super|Shift,  action: SpawnNewInstance  }
  - { key: Return,  mods: Control,      chars: "\x1b[13;5u"       }

window:
  dimensions:
    columns: 88
    lines: 28

font:
  normal:
    family: "Noto Sans Mono NerdFont"
    style: Regular
  bold:
    family: "Noto Sans Mono NerdFont"
    style: Bold
  italic:
    family: "Noto Sans Mono NerdFont"
    style: Italic
  bold_italic:
    family: "Noto Sans Mono NerdFont"
    style: Bold Italic
